# Set environment variables
$env:inp_text = "C:\Users\EVO\Documents\AI\GPT-SoVits\data\2b\filelists\train.list"
$env:inp_wav_dir = "C:\Users\EVO\Documents\AI\GPT-SoVits\data\2b"
$env:exp_name = "2b"
$env:opt_dir = "C:\Users\EVO\Documents\AI\GPT-SoVits\data\2b"
$env:cnhubert_base_dir = "C:\Users\EVO\Documents\AI\GPT-SoVits\models\cnhubert"
$env:i_part = "0"
$env:all_parts = "1"
$env:is_half = "True"
$env:PYTHONPATH = "C:\Users\EVO\Documents\AI\GPT-SoVits;C:\Users\EVO\Documents\AI\GPT-SoVits\GPT_SoVITS;C:\Users\EVO\Documents\AI\GPT-SoVits\tools"